exclude:
- branch: docs
- branch: cloned
- label: ignore-me
- label: contains-pii
switchComment: >
  Hey @{{author}}, the base branch of your pull request has been changed
  to {{preferredBranch}}. Have a nice day! :wave:
